name: Android E2E (Appium + WDIO)

on:
  push:
    branches: [ main ]
    paths:
      - "tests/**"
      - "wdio.conf.ts"
      - "package.json"
      - ".github/workflows/mobile-e2e.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "tests/**"
      - "wdio.conf.ts"
      - "package.json"

jobs:
  android-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install deps
        run: |
          npm ci
          npx appium driver install uiautomator2

      - name: Start Appium (bg)
        run: |
          npx appium --base-path /wd/hub --log-level error &
          echo $! > appium.pid
          sleep 3

      - name: Run tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: Pixel 5
          headless: true
          disable-animations: true
          script: |
            adb devices
            # opcional: garanta permissões ao APK se necessário
            # adb shell pm grant com.wdiodemoapp android.permission.POST_NOTIFICATIONS || true

            # Rodagem mais estável no CI
            npm run test:android -- --maxWorkers=1

      - name: Upload WDIO reports (sempre)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wdio-reports
          path: |
            reports/**
            ./**/wdio-*.log
            ./**/junit-*.xml
          if-no-files-found: ignore

      - name: Stop Appium
        if: always()
        run: |
          if [ -f appium.pid ]; then kill $(cat appium.pid) || true; fi
